<?php

/**
 * @file
 * Contains we_accessibility.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_help().
 */
function we_accessibility_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the we_accessibility module.
    case 'help.page.we_accessibility':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Accessibility Block') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function we_accessibility_theme($existing, $type, $theme, $path) {
  return [
    'we_accessibility' => [
      'render element' => 'block',
      'template' => 'we-accessibility',
      'variables' => [
        'form' => NULL
      ],
    ],
  ];
}

function we_accessibility_preprocess_html(&$variables) {
  $tempstore = \Drupal::service('tempstore.private')->get('we_accessibility');
  $fontSize = $tempstore->get('font_size');
  $lineHeight = $tempstore->get('line_height');
  $contrast = $tempstore->get('contrast');
  $noStyles = $tempstore->get('options[u-no-styles]');
  $noColors = $tempstore->get('options[u-no-colors]');
  if (is_array($variables['attributes'])) {
    $variables['attributes'] = new Attribute();
  }
  $variables['html_attributes']->addClass([$fontSize,$lineHeight,$contrast,$noStyles,$noColors]);
}
